# Generated by Django 5.1.7 on 2025-03-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="student",
            name="graduation_year",
        ),
        migrations.RemoveField(
            model_name="student",
            name="major",
        ),
        migrations.RemoveField(
            model_name="student",
            name="skills",
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in_process", "In Process"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("trash", "Trash"),
                ],
                default="active",
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
