# Generated by Django 5.1.7 on 2025-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_user_groups_remove_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="member_limit",
            field=models.IntegerField(
                choices=[(2, "2"), (3, "3"), (4, "4")], default=4
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="skills_required",
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in_process", "In Process"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("trash", "Trash"),
                ],
                default="in_process",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="skills_required",
            field=models.ManyToManyField(blank=True, to="projects.skill"),
        ),
    ]
