# Generated by Django 5.1.7 on 2025-03-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0003_skill_alter_project_member_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="advisor_images/"),
        ),
        migrations.AddField(
            model_name="project",
            name="author_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="author_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="advisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.advisor",
            ),
        ),
    ]
