# Generated by Django 5.1.7 on 2025-03-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "projects",
            "0004_advisor_image_project_author_id_project_author_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="author_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="author_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
