# Generated by Django 5.2 on 2025-04-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_author_id_alter_project_author_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_process", "In Process"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("trash", "Trash"),
                ],
                default="in_process",
                max_length=15,
            ),
        ),
    ]
