# Generated by Django 5.2 on 2025-04-30 09:40

import project_manager.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', project_manager.managers.CustomUserManager()),
            ],
        ),
    ]
