# Generated by Django 5.2 on 2025-04-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='project_manager.skill'),
        ),
    ]
