# Generated by Django 5.2 on 2025-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_project_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member_limit',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4')], default=4),
        ),
    ]
